schools_src/feeds/urls.py
from django.conf.urls import url

from feeds import views  
     # (?P<id>\d+)/ 
urlpatterns = [    
    url(r'^$', views.feeds, name='feeds'),
    url(r'^(?P<id>\d+)/$', views.feed, name='feeds'),
    url(r'^challenge/(?P<id>\d+)/$', views.specialfeeds, name='special_feeds'),
    url(r'^people/$', views.profilefeeds, name='profilefeeds'),    
    url(r'^products/$', views.product_profilefeeds, name='product_profilefeeds'),    
    # url(r'^challenge/(?P<id>\d+)/$', views.specific_challenge_feeds, name='specific_challenge_feeds'),    
    url(r'^challenge/$', views.challengefeeds, name='challenge_feeds'),
    url(r'^new_post/$', views.new_post, name='new_post'),
    url(r'^post/$', views.post, name='post'),
    url(r'^like/$', views.like, name='like'),
    url(r'^profile_like/$', views.profile_like, name='profile_like'),    
    url(r'^comment/$', views.comment, name='comment'),  
    url(r'^load/$', views.load, name='load'), 
    url(r'^check/$', views.check, name='check'), 
    url(r'^load_new/$', views.load_new, name='load_new'),
    url(r'^update/$', views.update, name='update'),
    url(r'^profile_update/$', views.profile_update, name='profile_update'),    
    url(r'^track_comments/$', views.track_comments, name='track_comments'),
    url(r'^remove/$', views.remove, name='remove_feed'),
    url(r'^(\d+)/$', views.feed, name='feed'),
] 
      

schools_src/mission_ajax/urls.py
from django.conf.urls import url
from .views import (
	basics,
	effects,
	interactions,
	widgets, 
	file_upload,
	test,
	)
from . import views

urlpatterns = [

	url(r'^$', basics, name='basics'),
	url(r'^effects$', effects, name='effects'),
	url(r'^interactions$', interactions, name='interactions'),
	url(r'^widgets$', widgets, name='widgets'),
	url(r'^test$', test, name='test'),
	# url(r'^file_upload$', file_upload, name='file_upload'),
	# url(r'^basic-upload/$', views.BasicUploadView.as_view(), name='basic_upload'),

]

schools_src/schools/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static  
from django.contrib import admin   
from django.contrib.auth import views as auth_views

from activities import views as activities_views
from authentication import views as schools_auth_views
from core import views as core_views
from search import views as search_views
from newsletter.views import (
    about, contact, home_out,
    )  
from django.contrib.auth.views import (
    password_reset,
    password_reset_done,
    password_reset_confirm, 
    password_reset_complete,  
    )
  
 
urlpatterns = [      
  
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', core_views.home , name='home'),
    url(r'^mission_ajax/', include('mission_ajax.urls', namespace='ajax')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^login', auth_views.login, {'template_name': 'core/cover.html'},
        name='login'), 
    url(r'^logout', auth_views.logout, {'next_page': '/'}, name='logout'),

    url(r'^signup/teachers$', schools_auth_views.signup_teachers, name='signup_teachers'),
    url(r'^signup/students$', schools_auth_views.signup_human, name='signup_human'),
    url(r'^signup/colleges$', schools_auth_views.signup_products, name='signup_products'),    
    
    url(r'^password_reset/$', password_reset, name='password_reset'),
    url(r'^password_reset/done/$', password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
                password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', password_reset_complete, name='password_reset_complete'),


    url(r'^contact/$', contact, name='contact'),
    url(r'^about/$', about, name='about'),
    url(r'^introho/$', core_views.introho, name='introho'),
    url(r'^settings/human/$', core_views.settings_human, name='settings_human'),
    url(r'^settings/products/$', core_views.settings_products, name='settings_products'),
    url(r'^settings/picture/$', core_views.picture, name='picture'),
    # url(r'^settings/upload_picture/$', core_views.upload_picture,
    #     name='upload_picture'), 
    # url(r'^settings/save_uploaded_picture/$', core_views.save_uploaded_picture,
    #     name='save_uploaded_picture'),
    url(r'^settings/profile_pic_upload/$', core_views.profile_pic_upload, name='profile_pic_upload'),
    url(r'^settings/password/$', core_views.password, name='password'),

    url(r'^network/$', core_views.network, name='network'),
    url(r'^feeds/', include('feeds.urls')),
    url(r'^notifications/$', activities_views.notifications,
        name='notifications'), 
    url(r'^notifications/last/$', activities_views.last_notifications,
        name='last_notifications'),
    url(r'^notifications/check/$', activities_views.check_notifications,
        name='check_notifications'),
    url(r'^search/$', search_views.search, name='search'),
    url(r'^searchusers/$', search_views.searchusers, name='searchusers'),
    url(r'^(?P<username>[^/]+)/$', core_views.profile, name='profile'),
    url(r'^(?P<username>[^/]+)/likers/$', core_views.profile_likers, name='profile_likers'),
    url(r'^(?P<username>[^/]+)/likesto/$', core_views.likes_to, name='likes_to'),
    url(r'^(?P<username>[^/]+)/activities/$', core_views.userfeeds, name='userfeeds'),
    url(r'^like/$', core_views.profile, name='profile_like'),
    url(r'^(?P<username>[^/]+)/$', core_views.profile_unlike, name='profile_unlike'),
    url(r'^i18n/', include('django.conf.urls.i18n', namespace='i18n')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

schools_src/schools/templates/base.html
{% load staticfiles i18n %} 

<!DOCTYPE html>  
<html lang="en"> 
  <head> 
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}welcome Hohos{% endblock %}</title> 
   {% block content_title %}
   {% endblock %}
   
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">  
<!--     <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">  
 -->    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static 'css/hohos.css' %}?v=1" rel="stylesheet"> 
    <!--[if lt IE 9]> 
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>    
    <![endif]-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <script src="{% static 'js/hohos.js' %}"></script>
 
  {% block head %}
  {% endblock %}  
  
  </head>
  
  <body style="background-color: #f2f2f2;">

    {% block body %}

    {% include 'header.html' %}
      <main>
      {% block jumbotron %}
      {% endblock %}
        <div class="container">
          {% block main %}
          {% endblock main %}
        </div>
        <div class="container-fluid">
          {% block main_fluid %}

          {% endblock main_fluid %}
        </div>
      </main>
      
<!-- <script src="{% static 'js/notifications.js' %}"></script> -->

    {% endblock body %}
    
    <!-- Here u can add a script to track how users visit the website -->
  {% block footer %}
  {% endblock %}
  </body>
</html>
 

schools_src/schools/templates/header.html
     {% load staticfiles %}
      {% load i18n %} 
 
{% block head %}
  <style> 
  .navbar-fixed-top{
  margin-bottom: 0px !important;
  background-color: #008080; 
  }

{% if "/products/" in request.get_full_path %}
 nav li:hover{
  cursor: pointer;
  background-color: #621120;     #400403
}   
{% elif "/challenge/" in request.get_full_path %}
 nav li:hover{
  cursor: pointer;   
  background-color: #2277AA;    A020F0 
} 
{% else %}
 nav li:hover{
  cursor: pointer;   
  background-color: #008B5E; 
} 
{% endif %} 
  </style> 
{% endblock %}

      <header> 
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
          <div class="container"> 
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#menu">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button> 
              <a class="navbar-brand" href="{% url 'introho' %}" style="font-family: Georgia, serif, cursive; color: white">{% trans 'schools' %}</a>
            </div>
            <div class="collapse navbar-collapse" id="menu">
              <ul class="nav navbar-nav">
                {% if request.user.is_authenticated %}
                <li>
                  <a href="#" id="notifications" data-container="body" data-toggle="popover" data-placement="bottom" title="Notifications">
                    <span class="glyphicon glyphicon-bell"></span>
                  </a>
                </li>
                <li><a href="{% url 'feeds' %}" style="color: white">{% trans 'home' %}</a></li>
            <!--     <li><a href="{% url 'profilefeeds' %}" style="color: white">{% trans 'PeopleLive' %}</a></li>
              <li><a href="{% url 'product_profilefeeds' %}" style="color: white">{% trans 'ProductsLive' %}</a></li> -->
              {% else %}
            <!--   <li><a href="{% url 'about' %}" style="color:white; font-size:20px;">{% trans 'We are here' %}</a></li> -->
              {% endif %}

              </ul>

{% if request.user.is_authenticated %}
<div class="btn-group pull-right" style="margin-top:8px;">
  
  {% if request.user.profile.is_product %}
  <a href="{% url 'profile' user.username %}" class="btn btn-danger" style="color: white">{{ user.profile.get_screen_name }}</a>
  <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <span class="caret"></span>
    <span class="sr-only">

      Toggle Dropdown</span>
  </button>
  {% else %}
  <a href="{% url 'profile' user.username %}" class="btn btn-success" style="color: white">{{ user.profile.get_screen_name }}</a>
  <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <span class="caret"></span>
    <span class="sr-only">

      Toggle Dropdown</span>
  </button>
  {% endif %}
  <ul class="dropdown-menu">
    <!-- <li><a href="#">Notifications</a></li> -->
    <li><a href="{% url 'userfeeds' user.username %}"><i class="fa fa-user fa-1x fa-fw"></i> my Activities</a></li>
    {% if request.user.profile.is_product %}
    <li><a href="{% url 'settings_products' %}"><i class="fa fa-cog fa-1x fa-fw"></i>
     Settings</a></li>
    {% else %}
    <li><a href="{% url 'settings_human' %}"><i class="fa fa-cog"></i>
    Settings</a></li>
    {% endif %}

    <li><a href="{% url 'logout' %}">
    <i class="fa fa-sign-out fa-1x fa-fw"></i> Logout</a>
    </li>

    <li><a href="{% url 'about' %}">
    <i class="fa fa-superpowers fa-1x fa-fw"></i> About schools</a>
    </li>

    <li role="separator" class="divider"></li>
    <li><a href="{% url 'contact' %}">
    <i class=" fa fa-question-circle fa-fw"></i> Support</a>
    </li>

    <li><a href="{% url 'network' %}">Community</a></li> 
    <li><a href="{% url 'ajax:basics' %}">Testing</a></li>
  </ul>
</div>
{% else %}
<div class="btn-group pull-right" style="margin-top:8px; margin-left:10px;">
  <a href="{% url 'signup_human' %}" class="btn btn-success" style="color: white">Come on Ho</a>
  <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <span class="caret"></span>
    <span class="sr-only"> 

      Toggle Dropdown</span>
  </button>
  <ul class="dropdown-menu">
    <!-- <li><a href="#">Notifications</a></li> -->
<!--     <li><a href="#">my Activities</a></li>
    <li><a href="#">Settings</a></li> -->
    <li><a href="{% url 'about' %}">
    <i class="fa fa-superpowers fa-1x fa-fw"></i>  About schools</a>
    </li>
    <li><a href="{% url 'contact' %}">
    <i class="fa fa-meetup fa-1x fa-fw"></i>Contact</a>
    </li>
    <li role="separator" class="divider"></li>
    <li><a href="{% url 'contact' %}">
    <i class=" fa fa-question-circle fa-1x fa-fw"></i> Support</a>
    </li>
  </ul>
</div>
{% endif %}

  {% if not request.user.is_authenticated and not "/signup/" in request.get_full_path %} 
            <form class='navbar-form navbar-right' method='POST' action='{% url "login" %}'>  
            {% csrf_token %}
              <div class='form-group'>
                  <input type='text' class='form-control' name='username' placeholder='Username' /> 
              </div>
              <div class='form-group'>
                  <input type='password' class='form-control' name='password' placeholder='Password' />
              </div>
              <button type='submit' class='btn btn-default'>Login</button>
          </form>
          {% else %}

              <div class="pull-right">
              {% if not hide_search %}
                <form class="navbar-form navbar-left" role="search" action="{% url 'search' %}">
                  <div class="input-group" style="width:250px">
                    <input type="text" class="form-control" name="q" placeholder="Search">
                    <span class="input-group-btn">
                      <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
                    </span>
                  </div>
                </form>
              {% endif %}
              </div>
              {% endif %}

            </div>
          </div>
        </nav>
      </header>

schools_src/schools/templates/markdown_editor.html
{% load staticfiles %}
<script src="{% static 'js/jquery.selection.js' %}"></script>
<script src="{% static 'js/hohos.markdown.js' %}"></script>

<div class="markdown">
  <div class="modal fade" id="markdown_insert_link">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Insert Link</h4>
        </div>
        <div class="modal-body">
          <div class="form-group">
            <label for="markdown_link_text" class="control-label">Link Text</label>
            <input type="text" class="form-control" id="markdown_link_text" placeholder="Link Text">
          </div>
          <div class="form-group">
            <label for="markdown_url" class="control-label">URL</label>
            <input type="text" class="form-control" id="markdown_url" placeholder="URL">
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-primary add_link" data-dismiss="modal">Ok</button>
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
  <div class="modal fade" id="markdown_insert_picture">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Insert Image</h4>
        </div>
        <div class="modal-body">
          <div class="form-group">
            <label for="markdown_picture_url" class="control-label">Picture URL</label>
            <input type="text" class="form-control" id="markdown_picture_url" placeholder="Picture URL">
          </div>
          <div class="form-group">
            <label for="markdown_alt_text" class="control-label">Alt Text</label>
            <input type="text" class="form-control" id="markdown_alt_text" placeholder="Alt Text">
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-primary add_picture" data-dismiss="modal">Ok</button>
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
  <div class="modal fade" id="markdown_help">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Help</h4>
        </div>
        <div class="modal-body">
          <p>You can learn more about markdown syntax <a href="http://daringfireball.net/projects/markdown/syntax" target="_blank">here</a>.</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
  <div class="btn-group">
    <button type="button" class="btn btn-default btn-sm" ref="header"><span class="glyphicon glyphicon-header"></span></button>
    <button type="button" class="btn btn-default btn-sm" ref="bold"><span class="glyphicon glyphicon-bold"></span></button>
    <button type="button" class="btn btn-default btn-sm" ref="italic"><span class="glyphicon glyphicon-italic"></span></button>
    <button type="button" class="btn btn-default btn-sm" ref="list"><span class="glyphicon glyphicon-list"></span></button>
    <button type="button" class="btn btn-default btn-sm" ref="link"><span class="glyphicon glyphicon-link"></span></button>
    <button type="button" class="btn btn-default btn-sm" ref="picture"><span class="glyphicon glyphicon-picture"></span></button>
    <button type="button" class="btn btn-default btn-sm" ref="indent-left"><span class="glyphicon glyphicon-indent-left"></span></button>
    <button type="button" class="btn btn-default btn-sm" ref="indent-right"><span class="glyphicon glyphicon-indent-right"></span></button>
  </div>
  <button type="button" data-toggle="modal" data-target="#markdown_help" class="btn btn-link btn-sm pull-right"><span class="glyphicon glyphicon-question-sign"></span> Help</button>
</div>
<script>$(function(){$("#{{ textarea }}").markdown();});</script>

schools_src/schools/templates/paginator.html
<ul class="pagination">
  {% if paginator.has_previous %}
    <li><a href="?page={{ paginator.previous_page_number }}">&laquo;</a></li>
  {% else %}
    <li class="disabled"><span>&laquo;</span></li>
  {% endif %}
  {% for i in paginator.paginator.page_range %}
    {% if paginator.number == i %}
      <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
    {% else %}
      <li><a href="?page={{ i }}">{{ i }}</a></li>
    {% endif %}
  {% endfor %}
  {% if paginator.has_next %}
    <li><a href="?page={{ paginator.next_page_number }}">&raquo;</a></li>
  {% else %}
    <li class="disabled"><span>&raquo;</span></li>
  {% endif %}
</ul> 